### ISSUE TITLE
Update codebase for SS4

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp#1]
~~Use namespace `SilverStripe\CWP`.~~ Use `CWP\CWP`

Sub-tasks can be added separately or as items in a checklist on this issue.
  
## Pull requests

- [x] #12
- [x] #13 
- [x] silverstripe/cwp-starter-theme#12
- [x] #15 

## Sub task issues

- [x] #9
- [x] #14 
- [x] #16 
- [x] #17 
- [x] #18 
- [x] #19 
- [x] #21 
- [x] #28

**Comment by phptek** [comment]
@robbieaverill I'm glad I checked here first - I went looking for the latest activity on gitlab.cwp.govt.nz. 

Mate, when are you and your team due to start on the CWP upgrade work and how long might it take? Only I need to do the same thing before 2.0 actually emerges and I'm keen not to duplicate effort. 

Thanks (and is there any SS project that _doesn't_ have a commit-in from you!? ;-)

**Comment by phptek** [comment]
There may be some opportunity for collaboration here, I'll keep you posted.

**Comment by robbieaverill** [comment]
Hey @phptek 

@tractorcow and I are going to move over the repos tomorrow morning in their current state, then will set up a 2.x-dev alias on the master branch.

If you're keen to help out with upgrade work that'd be awesome!

Our priority (in order) will be:

* cwp/cwp-core
* cwp/cwp
* cwp/agency-extensions
* cwp/starter-theme
* cwp/watea-theme

The installer and the recipes will come later - we're going to have some discussions internally about the feature sets we want to use for the recipes first.

Also, here's one :) https://github.com/silverstripe/silverstripe-redirectedurls

**Comment by phptek** [comment]
Hi @robbieaverill question: Does your plan for the 2 initial CWP package upgrades involve any new functionality? Or will 2.0 when released, comprise _exactly_ the same functionality, and just made to work with SS4 and its small handful of upgraded module deps?

**Comment by robbieaverill** [comment]
Hey @phptek 

Our plan for CWP 2.0 is that it will be functionally equivalent to CWP 1.0, but running on SilverStripe 4.

There are some changes that will be made, for example we'll be switching Translatable for Fluent.

Hope this helps!

**Comment by phptek** [comment]
@robbieaverill Thanks, and yes it does :-)

**Comment by tractorcow** [comment]
> Hi @robbieaverill question: Does your plan for the 2 initial CWP package upgrades involve any new functionality? Or will 2.0 when released, comprise exactly the same functionality, and just be made to work with SS4 and its small handful of upgraded module deps?


Actually, some of it has LESS functionality. We are dropping a bunch of modules that don't really make sense in 4.0 (e.g. versioned assets, protected files).

**Comment by phptek** [comment]
@tractorcow thanks, understood.

**Comment by NightJar** [comment]
Thanks for all the hard work team. All the subtasks are checked now, does anyone anticpate more being added, or should this issue be closed now? (more can always be made as separate issues).

**Comment by robbieaverill** [comment]
Nice - let's track new issues as they come. We can tag beta once #28 is merged

**Comment by NightJar** [comment]
Ok, merged :>
