### ISSUE TITLE
SiteTree breaks with larger number of pages in it

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp#101]
Copy of core issue: https://github.com/silverstripe/silverstripe-cms/issues/2183

Could be related to a previous issue introduces in 3.6.x which was reverted, reported to cause problems in subsites: https://github.com/silverstripe/silverstripe-subsites/issues/286

Related issues:

* https://github.com/silverstripe/silverstripe-cms/issues/2183
* https://github.com/silverstripe/silverstripe-subsites/issues/286
* https://github.com/silverstripe/silverstripe-framework/pull/7035
* https://github.com/silverstripe/silverstripe-framework/pull/7182

**Comment by ScopeyNZ** [comment]
Working on this, it appears 3.7 is the first release line that actually has this PR: silverstripe/silverstripe-framework#7035. Both 3.5 and 3.6 have a revert commit in them.

The PR seems way too opinionated on [this line](https://github.com/silverstripe/silverstripe-framework/pull/7035/commits/5b6a39e71a61fd595a913788c412b8e249611bff#diff-3c0bdb9680a5ae8e6873a9e209640483R162). Simply "If there's more than 30 pages, just don't show anything" - This is obviously breaking any site tree level that has more than 30 items, even the base level - so the tree is just empty.

Should we just pull through the revert or should I work on trying to make it work with what's done in that PR?

**Comment by robbieaverill** [comment]
Are we able to increase that threshold with configuration, or even disable it? We probably need more context from those initially involved with the change. cc @mfendeksilverstripe @dhensby

**Comment by ScopeyNZ** [comment]
There is configuration for that threshold - `Hierarchy.node_threshold_total` but it appears to be ignored. By default there's a hardcoded "30" and this is only overridden by config if the limit comes through as `null`.

I've done some work locally to get the tree showing at the root level regardless of the threshold - it does not look right at all if you have more than 30 pages and you just get a blank site tree section. There's a couple of things I think this needs for it to be ready for release though:

- Node count threshold should be configuration based not hard coded. This should be as simple as removing a default argument value (changing it to null)
- There should be some UX prompt when there's no items showing from exceeding the threshold. Especially as applying a search or other filters might make them show again...

Robbie pointed out that this is the last opportunity to get this going in SS3 so revert might be overkill, but again this feature has been sitting awaiting release for a year.

**Comment by dhensby** [comment]
> There should be some UX prompt when there's no items showing from exceeding the threshold. Especially as applying a search or other filters might make them show again...

the thing is, this shouldn't be possible... If a node has too many children then it should be lazy loaded, the direct descendants can be greater than the node_threshold, it's all the subsequant nested nodes that should be throttled by that threshold...

I wasn't really clear enough on the original optimised PR to be able to make a decent decision on it, but if it's broken it needs to be reverted, not matte the performance improvements. broken is worse than slow.

**Comment by robbieaverill** [comment]
Ok the change in core has been reverted, so we will update the core versions to 3.7.1 in CWP 1.9.0 and include that to fix this issue
