### ISSUE TITLE
Published pages are not being reported as published

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp#102]
Surfaced from an advancedworkflow unit test failure breakage over the past 2 days.

Example of some test failures: https://travis-ci.org/symbiote/silverstripe-advancedworkflow/builds/390579698

```php
    public function testPublishAction()
    {
        $this->logInWithPermission();

        $action = new PublishItemWorkflowAction;
        $instance = new WorkflowInstance();

        $page = new SiteTree();
        $page->Title = 'stuff';
        $page->write();

        $instance->TargetClass = SiteTree::class;
        $instance->TargetID = $page->ID;

        $this->assertFalse($page->isPublished());

        $action->execute($instance);

        $page = DataObject::get_by_id(SiteTree::class, $page->ID);
        $this->assertTrue($page->isPublished());
    }
```

In this example, `$action->execute($instance)` essentially calls this logic:
```php
Versioned::get_by_stage($this->TargetClass, Versioned::DRAFT)->byID($this->TargetID)->publishSingle()
```

This is essentially saying "create a page, assign it to the PublishItemWorkflowAction, check the page is unpublished, run the workflow (see above logic) then check that it IS published."

This test passes on SilverStripe 4.0 and 4.1 but is now failing on 4.2.

**NOTE:** this test was run in the context of the CWP kitchen sink recipe. It's passing with only the advancedworkflow module. Kitchen sink example failure: https://travis-ci.org/silverstripe/cwp-recipe-kitchen-sink/jobs/391582497

**Comment by maxime-rainville** [comment]
I'm pretty sure part of the problem is with this bit in [FluentExtension](https://github.com/tractorcow/silverstripe-fluent/blob/e6e1d03c37ce1a396b2cedb591c2b2809bd3ff06/src/Extension/FluentExtension.php#L475-L478):
```php
    public function onBeforeWrite()
    {
        $this->owner->forceChange();
    }
```

When I comment it out, the test passes. Not quite sure if it's a bug with Fluent, Versioned, or a bit of both. Any views on this one @tractorcow ?

I'll dig further down in the rabbit hole tomorrow.

**Comment by tractorcow** [comment]
That line is to force a write in the current locale. What we can replace that with, is a check to see if the record is localised in the current locale. If It's not, it needs the force write invoked.

Without it, loading a page in a different locale and pressing "save" won't actually make the page available in this locale.

**Comment by tractorcow** [comment]
Maybe a task for @robbieaverill one day :)

**Comment by robbieaverill** [comment]
“One day” -> tomorrow 😂

**Comment by robbieaverill** [comment]
From @tractorcow:

We have an `onBeforeWrite() { $this->owner->markChanged(); }` in fluent, that markChanged needs a very precise if() around it.

I think it'll be something like "if the current version ID does not match the localised version ID in the localised table of the current locale, then mark changed", because it can be changed "in memory" but it can be also changed due to a change in the current locale.

```php
$record = Record::get()->first();
// should not be changed
FluentState::singleton()->setLocale('anotherlocale');
// now it should be changed
$record->write();
// now it should not be changed
```

I think matching version ID should be enough, e.g. `SELECT COUNT(*) FROM "<table>_Localised_Version" WHERE "Version" = {$this->Version} AND "RecordID" = {$this->ID} and "Locale" = {$locale}` - if it's false, force a change

**Comment by tractorcow** [comment]
In my gut I think this'll probably fix the issue, but do some testing. I'm not sure if the stage matters.

**Comment by robbieaverill** [comment]
I'm hoping I can use `FluentVersionExtension::existsInLocale()` here. There are existing tests that cover the `FluentExtension::onBeforeWrite()` functionality - just running some tests with updated logic to see how it fits.

**Comment by robbieaverill** [comment]
Fixed with https://github.com/tractorcow/silverstripe-fluent/pull/429
