### ISSUE TITLE
Advanced workflow tests cannot load a fixture

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp#106]
See: https://travis-ci.org/symbiote/silverstripe-advancedworkflow/jobs/390579701

This in combination with #105 and #104 makes me think that there's an incorrect change in how the test suites are compiled somewhere, after having been updated in the last two days.

Perhaps we're not resetting fixtured databases correctly, or something like that. Many of these tests pass when run individually, but fail in a suite (or a test class).

**Comment by robbieaverill** [comment]
Can confirm that these test failures are fixed by reverting transactions in SapphireTest (https://github.com/silverstripe/silverstripe-framework/pull/8178) cc @tractorcow

**Comment by tractorcow** [comment]
Simpler fix at https://github.com/symbiote/silverstripe-advancedworkflow/pull/364

**Comment by robbieaverill** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/8179
