### ISSUE TITLE
Cannot schedule jobs from CMS

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/cwp#117]
I triggered a job by clicking the refresh button within the Installed modules section. I then went to the Jobs section and clicked the play button to run the scheduled job. An alert with the following message pops up.

"An error occured while fetching data from the server"

The jobs status is not changing after dismissing the alert. When refreshing the page it shows as Broken.

When consequently trying to run the same scheduled job from the command line the following error is thrown:
```
Running Task Symbiote\QueuedJobs\Tasks\ProcessJobQueueTask

ERROR [UNKNOWN TYPE, ERRNO ]: Array
(
    [errno] => 0
    [errstr] => Broken jobs were found in the job queue
    [errfile] => /Users/raissa/dev/cwp210rc1/vendor/symbiote/silverstripe-queuedjobs/src/Services/QueuedJobService.php
    [errline] => 371
    [errcontext] => Array
        (
        )

)

IN GET dev/tasks/ProcessJobQueueTask
Line 378 in /Users/raissa/dev/cwp210rc1/vendor/symbiote/silverstripe-queuedjobs/src/Services/QueuedJobService.php
```

Without trying to run this job from the CMS first, it runs fine via the command line.

**Comment by robbieaverill** [comment]
I couldn't reproduce this:

* Log into the CMS
* Go to reports
* Go to "Installed modules" report
* Click "Generate report"
* Go to Jobs
* Click "play" icon to run job for "Check for updates job"

Expected: job runs, job completes, job rescheduled itself for 24 hours later

Actual: as above

**Comment by robbieaverill** [comment]
It could be that you have a low memory limit or maximum execution time in your local web server configuration. Note that long running jobs should not be run from the CMS interface, and we should probably indicate that better in some way.

**Comment by robbieaverill** [comment]
Feel free to reopen if this comes up again =)
