### ISSUE TITLE
Regression: Users with invalid email addresses prevent workflows from advancing.

### ISSUE THREAD

**Issue by NightJar** [silverstripe/cwp#119]
as per https://github.com/symbiote/silverstripe-advancedworkflow/issues/359

this issue is made as a duplicate for tracking purposes (c.f. Milestone), but could potentially also be read as "Make username requirements more strict - disallowing users to be created with emails that aren't emails".

Not a regression as such from CWP 2.0.0, but is when considering migration from 1.8.0.

**Comment by robbieaverill** [comment]
Removing from 2.1.0 milestone as it's unlikely we'll fix it by then - track progress on https://github.com/symbiote/silverstripe-advancedworkflow/issues/359
