### ISSUE TITLE
Image placement should replicate actual position in TinyMCE

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/cwp#120]
For CWP themes the CMS doesn't detect the position of image alignment, so there is a disconnect between the preview and whats displayed in TinyMCE. 

![image](https://user-images.githubusercontent.com/555033/41576650-bb42effa-73dc-11e8-9571-ed3f19f00a9a.png)

Image provided during CMS training.

**Comment by robbieaverill** [comment]
Issue moved to [silverstripe/silverstripe-cms #2202](https://github.com/silverstripe/silverstripe-cms/issues/2202) via [**ZenHub**](https://www.zenhub.com/)

**Comment by robbieaverill** [comment]
I've reproduced this in the SilverStripe demo site (4.1.0) so have moved it to the CMS module since it's not a CWP specific issue.
