### ISSUE TITLE
Formatting issues when copy/pasting from a Word document (affects IE11 only)

### ISSUE THREAD

**Issue by katieelks** [silverstripe/cwp#122]
Users have reported the attached formatting issues when copy/pasting from a Word document:
Please see attached docs - Issue 1 and Issue 2
The business want to be able to copy text only and not the table formatting. 
![issue 1](https://user-images.githubusercontent.com/38870753/41824515-891a9234-7865-11e8-9acd-de3649a96cf0.GIF)
![issue 2](https://user-images.githubusercontent.com/38870753/41824517-8a6e4180-7865-11e8-8ebd-d90e5231cbc8.JPG)

**Comment by robbieaverill** [comment]
Hey @katieelks,

SilverStripe CMS uses TinyMCE as its default WYSIWYG editor - this provides some basic support for copy and pasting rich text content, but it's not always going to get it right.

You can always paste as plain text and re-implement the formatting (e.g. list items) in TinyMCE afterwards. I would recommend this personally and tend to do this myself usually as I don't trust the HTML that WYSIWYG editors produce in general.

Your client may also wish to purchase an improved TinyMCE plugin (TinyMCE enterprise) which may help with this: https://www.tinymce.com/docs/enterprise/paste-from-word/

Other than the above options there isn't much that SilverStripe can do to solve this problem, so I'm going to close the issue for now. Please feel free to reopen if you disagree =)

**Comment by katieelks** [comment]
Thanks @robbieaverill that's helpful!
