### ISSUE TITLE
Cannot open /dev/tasks in browser on CWP or SSP

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp#124]
**CWP 2.1.0-beta1**

When a kitchen sink recipe is deployed to either CWP or SSP platform, the `/dev/tasks` URL cannot be used.

Expected: see list of tasks

Actual:

* 500 error (platform)
* 503 error (CWP)
* Server error page is displayed
* Server error page contains the simple theme markup. The simple theme is not in this project

While there are entries in Graylog for these requests, they provide no useful information other than the HTTP status code.

**Comment by robbieaverill** [comment]
So far what I've tried with @jakedaleweb:

* Clear the static error 404 and 500 pages from the assets folder, so that dev/build will regenerate them (trying to remove simple theme references)
* Set environment type to dev (from test) manually on the servers
* Check Graylog for errors

We also noticed two other things:

* Audit entries regularly for Member records being modified, possibly because of a last logged in date being set?
* /dev/tasks may redirect to /Security/login and back again in an infinite loop - we've seen this end in a 429 rate limiting HTTP response

I can't reproduce this locally with dev or test environment types, so we might need to collaborate with TSP to debug why this is happening.

**Comment by jakedaleweb** [comment]
Have seen similar issues in ss4 sites where there are silent errors. Previously this was caused by use of `SS_Log` (deprecated) to log the error or incorrect name-spacing on `Exception`.

Have confirmed that dev/tasks is accesible via CLI i.e. `framework/sake dev/tasks`

**Comment by robbieaverill** [comment]
>Have seen similar issues in ss4 sites where there are silent errors

Yeah - one problem is when `/dev/build` (for example) redirects somewhere, the exit code from `vendor/bin/sake dev/build` is zero which indicates success, yet nothing was done. It looks like the platform scripts check for empty output from these commands to determine failure though.

**Comment by robbieaverill** [comment]
Following up from https://github.com/bringyourownideas/silverstripe-maintenance/issues/113, this is fixed. In this module there is a build task that has a dependency (via Injector) which is throwing a RuntimeException during construction - this is not being handled by SilverStripe's error handler, so was returning a 503 with no useful information at all to debug it.

@NightJar I think we should log an issue for this on framework so it can be fixed

**Comment by robbieaverill** [comment]
Fixed via https://github.com/bringyourownideas/silverstripe-maintenance/issues/113#issuecomment-399839813
