### ISSUE TITLE
Content editor not showing on CWP

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/cwp#129]
__CWP 1.9.0-rc1__

When 1.9.0-rc1 is deployed to CWP the content WYSIWYG is not displayed:

![image](https://user-images.githubusercontent.com/3260989/42003845-6e6bc454-7ac1-11e8-9fde-fd6d3f52b6ea.png)

**Comment by robbieaverill** [comment]
Any console errors?

**Comment by ScopeyNZ** [comment]
Nope.

**Comment by NightJar** [comment]
From experience (this is a semi-regular although infrequent thing in community channels) there is probably a network error though (ie. `404 tinymce.gz` or whatever it is). Could you please confirm?

**Comment by ScopeyNZ** [comment]
The only 404 is a favicon :( - Usually 404s on stylesheets or script show up in the console but in this case it's nothing. I looked up tiny_mce_gzip.php in console "Sources" view and it appears to be valid.

**Comment by NightJar** [comment]
And [our friend here](https://github.com/silverstripe/silverstripe-framework/blob/3.7/forms/HtmlEditorField.php#L188) is present and loaded?
If so, then I would look for things that have been modified, such as the selectors that trigger the instantiation.

**Comment by ScopeyNZ** [comment]
I'm terrible. `?flush` worked... 😞

**Comment by chillu** [comment]
We're one patch release behind TinyMCE (3.5.11 vs. [3.5.12](https://www.tinymce.com/download/older-releases/)  on that release line). I can't find any statements from TinyMCE if they still support 3.x. No indication of actioning existing 3.x bugs in https://github.com/tinymce/tinymce/issues. Given the last 3.x release was in 2012, I doubt it. So this might just be a matter of a complex JavaScript library no longer playing well with modern browser implementations.

Unfortunately, upgrading SilverStripe 3.x to TinyMCE 4.x is out of the question, unless this is a blocker for a large number of customers. We're technically in security-fixed only mode for SilverStripe 3.x release line.
