### ISSUE TITLE
next / previous article buttons broken

### ISSUE THREAD

**Issue by dhensby** [silverstripe/cwp#133]
The next and previous article buttons links are broken:

If you [navigate here](https://www.cwp.govt.nz/developer-docs/en/2/features/solr_search/running_solr_locally/) and then scroll to the bottom and click "Basic usage of Solr search >" you are directed to `https://developer-docs/en/2/features/solr_search/basic_usage/` (note the domain part is missing).

This doesn't appear to be a docsview issue as the SS docs don't suffer this problem

**Comment by robbieaverill** [comment]
Can't reproduce any more, so going to close
