### ISSUE TITLE
CWP 2.1.0 upgrade hides Insert image button

### ISSUE THREAD

**Issue by phalkunz** [silverstripe/cwp#144]
With this upgrade, the "Insert" button in attach/insert image dialog is hidden. The html class that hides it is `asset-admin--single-select`. 

![silverstripe_-_edit_page](https://user-images.githubusercontent.com/318116/43614939-8b2d4ba8-9709-11e8-97be-520850025447.png)

**Comment by robbieaverill** [comment]
@phalkunz where is this happening?

**Comment by phalkunz** [comment]
On a page with an upload field

```php
                $uploadField = UploadField::create('PrimaryImage', 'Feature image')
                    ->setDescription('Select a main image from the Files section.')
                    ->setUploadEnabled(false);
```

I also tried removing `setUploadEnabled(false)` and it didn't help.

**Comment by phalkunz** [comment]
@robbieaverill Any updates on this?

**Comment by robbieaverill** [comment]
@phalkunz I'll take a look on our next bug day

**Comment by phalkunz** [comment]
@ScopeyNZ I tried it again on a basic installation. I could see an insert button but it's in a different place and style. Is this how it's supposed to be now? 

![silverstripe_-_edit_page](https://user-images.githubusercontent.com/318116/44493060-becc7b80-a6ba-11e8-8fd3-80eaf879e8f9.png)

**Comment by ScopeyNZ** [comment]
I believe so. I was just about to reply and say "works for me". If you can't reproduce the problem any more with your code feel free to close this issue 🙂

**Comment by phalkunz** [comment]
@ScopeyNZ Thanks for confirming this 😃
