### ISSUE TITLE
DateField is in wrong (US) format instead of NZ format

### ISSUE THREAD

**Issue by pjayme** [silverstripe/cwp#147]
The issue occurs in IE11 and Firefox browsers, we have confirmed that we have set the locale correctly in the configs and CMS settings. 

This occurred with a custom field as well as an existing CMS field. 

```DateField::create('Date', 'Event date')```

This occurs in: SS4.2/CWP2.1

**Comment by robbieaverill** [comment]
@pjayme thanks, do you think this might be a core issue or specific to something CWP is doing?
