### ISSUE TITLE
"Insert Media from URL" fails with cURL error 23 when using an image

### ISSUE THREAD

**Issue by indygriffiths** [silverstripe/cwp#159]
```
$ composer info --direct
cwp/cwp-recipe-cms                  2.1.1  CWP CMS requirements recipe
cwp/cwp-recipe-core                 2.1.1  CWP core requirements recipe
cwp/cwp-recipe-search               2.1.1  CWP search requirements recipe
```
When using the "Insert Media via URL" functionality as part of the CMS with an image URL, the request fails with either `An unknown error has occurred` or `There is currently no embeddable media available from this URL`. 

Note that if this error occurs on CWP, the request may return as a 503 instead of 500 due to infrastructure quirks.

This doesn't appear to be a proxy issue, as the results from the cURL request sent as part of the `embed/embed` package bundled into the framework show the correct headers and status code, but there is an interesting cURL error suggesting the body of the response cannot be written (see the `error` key)

Test URL: https://i.ytimg.com/vi/75l9YdDrgvw/hqdefault.jpg

```
          'url' => string 'https://i.ytimg.com/vi/75l9YdDrgvw/hqdefault.jpg' (length=48)
          'content_type' => string 'image/jpeg' (length=10)
          'http_code' => int 200
          'header_size' => int 418
          'request_size' => int 148
          'filetime' => int -1
          'ssl_verify_result' => int 0
          'redirect_count' => int 0
          'total_time' => float 0.076335
          'namelookup_time' => float 0.02331
          'connect_time' => float 0.034689
          'pretransfer_time' => float 0.064441
          'size_upload' => float 0
          'size_download' => float 983
          'speed_download' => float 12877
          'speed_upload' => float 0
          'download_content_length' => float 10207
          'upload_content_length' => float 0
          'starttransfer_time' => float 0.075895
          'redirect_time' => float 0
          'redirect_url' => string '' (length=0)
          'primary_ip' => string '103.13.116.175' (length=14)
          'certinfo' => 
            array (size=0)
              ...
          'primary_port' => int 443
          'local_ip' => string 'xxx.xxx.xxx.xxx' (length=9)
          'local_port' => int 37320
          'error' => string 'Failed writing body (18446744073709551615 != 983)'
```

Test URL: https://via.placeholder.com/1200x500
```
          'url' => string 'https://via.placeholder.com/1200x500' (length=36)
          'content_type' => string 'image/png' (length=9)
          'http_code' => int 200
          'header_size' => int 322
          'request_size' => int 129
          'filetime' => int -1
          'ssl_verify_result' => int 0
          'redirect_count' => int 0
          'total_time' => float 0.929942
          'namelookup_time' => float 0.012863
          'connect_time' => float 0.237063
          'pretransfer_time' => float 0.704437
          'size_upload' => float 0
          'size_download' => float 3938
          'speed_download' => float 4234
          'speed_upload' => float 0
          'download_content_length' => float 3938
          'upload_content_length' => float 0
          'starttransfer_time' => float 0.929079
          'redirect_time' => float 0
          'redirect_url' => string '' (length=0)
          'primary_ip' => string '45.33.24.119' (length=12)
          'certinfo' => 
            array (size=0)
              ...
          'primary_port' => int 443
          'local_ip' => string 'xxx.xxx.xxx.xxx' (length=9)
          'local_port' => int 40204
          'error' => string 'Failed writing body (18446744073709551615 != 3938)' (length=50)
```

Have been able to reproduce this locally and on a CWP environment using both existing and freshly-created websites.

**Comment by indygriffiths** [comment]
This was resolved in the Embed library as part of [this issue](https://github.com/oscarotero/Embed/issues/293) so the fix should be updating this dependency when it's tagged.

**Comment by phptek** [comment]
FYI this has been merged to `master` https://github.com/oscarotero/Embed/commit/a28580412fae53fe046f8e5d365a73d839ce8f8f.

**Comment by brynwhyman** [comment]
@chillu can you please have a look at this one? I expect we'll want to get the `embed/embed` dependancy bumped in framework in time for the upcoming release. It doesn't look like @oscarotero has tagged the fix yet.

**Comment by ScopeyNZ** [comment]
We will just need to ask for a patch release of the library with the fix in it then we can bump the composer requirement.

**Comment by oscarotero** [comment]
Tag [v3.3.7](https://github.com/oscarotero/Embed/releases/tag/v3.3.7) released 😉

**Comment by ScopeyNZ** [comment]
Thanks @oscarotero . We don't need to do anything now. Framework has a fairly loose requirement `^3.0` so it'll be included in any future installs. :)
