### ISSUE TITLE
Cannot remove related pages, can only archive the related page itself

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp#179]
## Versions

CWP 2.2.x-dev

## Steps to reproduce

* Create Page A
* Create Page B
* Switch to Page A
* Go to Related Pages tab
* Link Page B to it
* Publish the page
* Try to unlink or delete the record for Page B as related page

## Expected

You should be able to either unlink or delete the related pages link record without affecting Page B

## Actual

You can only "Archive" the Page B link record, which actually deletes Page B.

## Acceptance criteria
- [ ] The action on the "related page" gridifeld is changed to "unlink" instead of delete.

**Comment by robbieaverill** [comment]
Related issue here: https://github.com/silverstripe/silverstripe-versioned/issues/200

**Comment by ishannz** [comment]
@robbieaverill one of our clients reported this as a bug. are you going to fix this anytime soon?

**Comment by robbieaverill** [comment]
Hi @ishannz, please jump on to https://github.com/silverstripe/silverstripe-versioned/issues/200 - we can't fix this in CWP until it's fixed there first

**Comment by maxime-rainville** [comment]
I'm not sure when this got fixed. But the menu is now showing both an Archived and Unlink action.

![image.png](https://images.zenhubusercontent.com/5ac42fb74b5806bc2bcd8e13/5c21af71-dd15-4244-84ef-f61726f1e1bd)
