### ISSUE TITLE
Create a release template

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/cwp#188]
**Overview**
While the actual _change log_ is generated during the release process, there's no clear template for what other information should be included in the release notes on CWP.govt.nz. This leads to inconsistent information being provided between releases. See [2.1.0](https://www.cwp.govt.nz/developer-docs/en/2/releases_and_changelogs/cwp_recipe_basic_2.1.0/) vs. [2.2.2](https://www.cwp.govt.nz/developer-docs/en/2/releases_and_changelogs/cwp_recipe_basic_2.2.2/).

**Suggested changes**
A new template should be created that includes the following headings. These could be added to or removed depending on what's contained in the release.
- Table of contents
- Overview
- New features
- Security changes
- Known issues
- Change Log
- Upgrading instructions

**How to generate the template**
To ensure this is easy to slid into the existing process the template should be easy to access and edit. Having it automatically created as part of the release process would be ideal.

**Comment by robbieaverill** [comment]
Cow enhancement issue: https://github.com/silverstripe/cow/issues/138

**Comment by brynwhyman** [comment]
Related to 'Known issues', we could add reference to our GitHub issue search client, something like:
"You can also use the [SilverStripe bug tracker](https://www.silverstripe.org/blog/searching-silverstripe-issues-just-got-a-lot-easier/) to review all open [high](https://silverstripe-github-issues.now.sh/?q=label%3Aaffects%2Fv4+label%3Atype%2Fbug+label%3Aimpact%2Fhigh) or [critical](https://silverstripe-github-issues.now.sh/?q=label%3Aaffects%2Fv4+label%3Atype%2Fbug+label%3Aimpact%2Fcritical) impact bugs"

**Comment by Cheddam** [comment]
Cow enhancement PR: https://github.com/silverstripe/cow/pull/140

**Comment by Cheddam** [comment]
Cow enhancement has been merged, PR for implementing the template in Kitchen Sink: https://github.com/silverstripe/cwp-recipe-kitchen-sink/pull/37

**Comment by robbieaverill** [comment]
All merged

**Comment by brynwhyman** [comment]
Reopening because the template wasn't updated in: https://github.com/silverstripe/cwp-recipe-kitchen-sink/blob/master/.changelog.md.twig

**Comment by brynwhyman** [comment]
Closed with https://github.com/silverstripe/cwp-recipe-kitchen-sink/issues/40
