### ISSUE TITLE
Page to link the "Learn More" button to is not used any more

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp#191]
**CWP 2.3.x-dev**

The BaseHomePage defines a `LearnMorePage` relationship and has a field on the home page's CMS fields main tab. This field isn't used anywhere by default, is possibly related to removing the features category icons which are no longer used in starter/watea either.

**Comment by GuySartorelli** [comment]
This is no longer a supported module - we aren't likely to be releasing new majors for it so removing API is out of scope.
