### ISSUE TITLE
FulltextSearch as an optional dependency should not be referenced directly

### ISSUE THREAD

**Issue by NightJar** [silverstripe/cwp#21]
Fulltext functionality is intended to be optional to the site's requirements, however is currently set as the default in all search related activities (c.f. `CWP\CWP\PageTypes\BasePageController.search_index_class` config setting) settings an out of the box dependency on what is unlisted as a requirement, and _should_ be optional.

This `cwp` module is intended to provide base plate type functionality that makes it easy to utilise e.g. a `SearchForm`, however it isn't necessarily used, nor if it is that it should be required to have an advanced Solr type setup (which the default provider subclasses).
`silverstripe/fulltextsearch` is extended (subclassed) directly in various places, however is not currently required (nor do I think should be) by this module, nor any of it's dependencies.

This issue is of two parts, one to separate out what is contained in this `cwp` repository, and the other to affect the `cwp-core` repository: https://github.com/silverstripe/cwp-core/issues/14

Ideally there'll be e.g. `cwp/cwp-search` or suchlike that would house the adaptive functionality that enables the features provided by/for the platform, rather than essentially having an unlisted dependency for this module.
 

## Pull requests

- [x] silverstripe/cwp-core#15
- [ ] silverstripe/cwp#30
- [ ] silverstripe/cwp-search#1

**Comment by robbieaverill** [comment]
I'm going to do this on top of the changes in https://github.com/silverstripe/cwp/pull/25 to avoid conflicts

**Comment by robbieaverill** [comment]
Repo created at github.com/silverstripe/cwp-search

**Comment by robbieaverill** [comment]
Pull requests added to the description
