### ISSUE TITLE
only run tinyMCE code when you need to

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/cwp#210]
I am wondering why this code:

https://github.com/silverstripe/cwp/blob/1f7ba0c0ee566329e981cdbf1609f3c94da4aa44/_config.php

Is in the global space.  Why not run that whenever an HTML editor is created? 

In the past, we have also hacked this to say that if the request url starts with /admin/, we run it.

**Comment by robbieaverill** [comment]
Closing as a duplicate of https://github.com/silverstripe/cwp/issues/139 =)

**Comment by sunnysideup** [comment]
;-)))) sorry! I did feel a little deja vu... ;-)
