### ISSUE TITLE
Spell out what CWP stands for …

### ISSUE THREAD

**Issue by cloph** [silverstripe/cwp#222]
"CWP" repo description reads: "We strongly recommend using it for all new sites" but doesn't bother to state what CWP actually stands for and what scope the recommendation applies to.

Google search reveils that it is apparently used in New Zealand by government-run sites and stands for Common Web Platform.

I shouldn't be forced to do a google search to find this out, so please add that to the repository's description and/or Readme. Thx :-)

**Comment by robbieaverill** [comment]
I've updated the repository's description and URL to make it a bit clearer:

>Common Web Platform (CWP) features module. We strongly recommend using it for all new sites. Future features will be delivered here. https://www.cwp.govt.nz

Thanks for reporting the issue =)
