### ISSUE TITLE
Update SearchEngine and BasePage to support PHP 7.2

### ISSUE THREAD

**Issue by sig-dan** [silverstripe/cwp#229]
Add support for PHP7.2 on latest SS 3.x branch (1)
changing Object references to SS_Object

required changes are:

BasePage.php
`        if (self::$search_index_class) {
            $index = SS_Object::singleton(self::$search_index_class);
        }
`

CwpSearchEngine.php
`class CwpSearchEngine extends SS_Object {
`

**Comment by robbieaverill** [comment]
CWP 1.9.2 will be released at the start of September which will support PHP 7.2+
