### ISSUE TITLE
No anchor functionality in TinyMCE

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/cwp#244]
## Overview
Anchor functionality was (re)introduced into TinyMCE with https://github.com/silverstripe/silverstripe-cms/issues/2268, however this functionality hasn't been ported to CWP.

## Steps to reproduce
1. Install silverstripe-installer @4.5-rc1; identify you can create and link to anchors in TinyMCE
2. Install cwp-installer @2.5-rc1 (4.5-rc1); identify no anchor functionality is present

## Expected behaviour
- Anchors can be created and linked to on a CWP installation

**Comment by NightJar** [comment]
This is because CWP uses an entirely different editor configuration named `cwp` as opposed to the default `cms`.
https://github.com/silverstripe/cwp/blob/2.5.0-rc1/_config.php#L16

**Comment by NightJar** [comment]
https://github.com/silverstripe/cwp/pull/245

**Comment by brynwhyman** [comment]
Closed with #245
