### ISSUE TITLE
Draft badge shows on just published carousel item

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/cwp#274]
2.x-dev - what will become 2.6.x-dev, tested as part of cwp regression testing

Logged in as a "Content Author"

Create a "Home Page" (extends BaseHomePage)

Add a `Carousel Item`

Upload a new image - it will show the draft badge

- the draft badge remained if I published the carousel item (instead of the page), though the image did actually publish

- publishing the page with a draft image on a draft carousel item did work as expected

**Comment by brynwhyman** [comment]
I'm pretty sure this is another example of: https://github.com/silverstripe/silverstripe-asset-admin/issues/960

**Comment by dhensby** [comment]
closing as duplicate

**Comment by michalkleiner** [comment]
Should CWP issues stay open until the underlying issues are resolved? It may seem like there are no issues with CWP because it's all within the underlying modules, but it might be painting a wrong picture of the state of things.

**Comment by brynwhyman** [comment]
I think this should remain closed with silverstripe/silverstripe-asset-admin#960 known as the issue, **unless there is something specific to the code in this module that is related.** 

Issues are not consistently linked to a corresponding CWP issue so I don't think it would be an accurate way to get an idea of the state of things. This `cwp/cwp` module provides _some_ functionality for the Silverstripe CMS and is not communicated to be a dedicated issue tracker for CWP sites built with Silverstripe CMS.
