### ISSUE TITLE
Builds broken on 2.3 branch

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/cwp#282]
The `2.3` builds are failing.

Looks to be a config issue?:
`PHP Warning:  mysqli::real_connect(): (HY000/2002): Connection refused in /home/travis/build/silverstripe/cwp/vendor/silverstripe/framework/src/ORM/Connect/MySQLiConnector.php on line 113`

https://travis-ci.org/github/silverstripe/cwp/builds/677545084

**Comment by emteknetnz** [comment]
It's a fairly old version so probably a lack of `dist: trusty` or `dist: xenial` in the `.travis.yml` file

Likely that travis infrastructure updated, though our `.travis.yml` config file was not updated

**Comment by brynwhyman** [comment]
There have been a number of minor releases since 2.3. Closing.
