### ISSUE TITLE
Remove 'CWP module' filter from maintenance report

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/cwp#289]
### Overview
I believe this module extends the [bringyourownideas/silverstripe-maintenance](https://github.com/bringyourownideas/silverstripe-maintenance) module to add a CWP-specific filter to the report. 

Without extending the report, logic in silverstripe/cms (I think) will provide a filter to view commercially supported/ unsupported modules.

I propose we remove the CWP-specific filtering for three reasons:
- It currently appears to not be entirely accurate. E.g. `cwp-core` and `admin` are noted as "Non CWP modules"
- This is and will be a maintenance burden as cwp recipes change as time goes on. 
- CWP modules and commercially supported modules are currently treated the same, so I don't see the added benefit of allowing CMS users to use this filter.

Report and filter in question:

![image](https://user-images.githubusercontent.com/15868440/87986791-af1d7200-cb31-11ea-8d9c-40b422f00d76.png)

### ACs
- CWP-specific filtering is removed from the CMS 'Installed Modules Report' (`bringyourownideas/silverstripe-maintenance`)
- The report is able to be filtered by commercially supported/ unsupported modules (see `silverstripe/installer` to see this in action)

**Comment by brynwhyman** [comment]
This is a bug. The solution (IMO) is to remove the feature.

**Comment by maxime-rainville** [comment]
Yeah ... we won't do that.
