### ISSUE TITLE
TinyMCE External link text issue in IE11 browser

### ISSUE THREAD

**Issue by roopamjain01** [silverstripe/cwp#290]
I am using silverstripe 4.3 and CWP 2.2 . 

When I added external link and clicked on the "inset link" button in the tinyMCE editor, it changed the link text to "undefined" in the IE11 browser.

I tried with other browser and it is working as expected.

**Comment by emteknetnz** [comment]
Originally reported in https://github.com/silverstripe/silverstripe-cms/issues/2512 and resolved in https://github.com/silverstripe/silverstripe-admin/pull/1059

@roopamjain01 to receive this update you'll need to upgrade to silverstripe/cms 4.6.1 which is part of CWP 2.6.1
