### ISSUE TITLE
Move PDF generation into a separate module

### ISSUE THREAD

**Issue by chillu** [silverstripe/cwp#31]
The majority of `BasePage` and `BasePageController` deal with generating PDFs. That's becoming a less common use case on the web, given that PDF is generally not considered an accessible format for government websites, and because browsers have that built in now (even on [Edge](https://www.laptopmag.com/articles/print-microsoft-edge)). 

Even if you don't use this feature on your website, the `downloadpdf` endpoint is accessible on every page - which increases the DDoS attack surface of every CWP site. It also increases the amount of code a SilverStripe dev needs to review and understand when coming into a CWP project.

Move this feature into a separate module (`cwp/pdfexport`?). I'd suggest to make it opt-in, and document an upgrade path. This will be an API change (method subclassing on `Page` no longer works). CWP 2.0 is an opportunity to do that.

You could argue that CWP no longer needs to provide this feature, and hence it shouldn't be a supported module within CWP in the first place (reducing our maintenance burden, e.g. with https://github.com/silverstripe/cwp/issues/3) - but that's a wider discussion that might not be resolved in the CWP 2.0 release timeline.

/cc @tractorcow @robbieaverill

**Comment by tractorcow** [comment]
This is a smaller part of the "refactor basepage away forever" that I'd like in cwp. How much of this can we do in 2.0 @robbieaverill ?

**Comment by robbieaverill** [comment]
Yeah why not :-D

**Comment by robbieaverill** [comment]
Pull requests:

* https://github.com/silverstripe/cwp/pull/32
* https://github.com/silverstripe/cwp-pdfexport/pull/1

**Comment by NightJar** [comment]
By the by, Edge is even now the _default_ PDF viewer in Windows.

**Comment by chillu** [comment]
🎉
