### ISSUE TITLE
CMS 5 - Installed modules report - CWP filter doesn't work

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/cwp#320]
Discovered as part of 5.0.0 beta testing

Filtering on CWP recipe modules - I see no results

Non-CWP works, though shows everything including 'cwp' module

Installed modules report uses bringyourownideas/silverstripe-maintainence SiteSummary report

cwp updates it with CwpSiteSummaryExtension

## Acceptance criteria
- [ ] CWP filter is removed.
- [ ] Other filters still work as expected.

## PRs
- https://github.com/silverstripe/cwp/pull/322
- https://github.com/silverstripe/cwp/pull/323
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/191
- https://github.com/silverstripe/developer-docs/pull/181

## Follow up card
- https://github.com/silverstripe/.github/issues/22

**Comment by GuySartorelli** [comment]
I think at this stage the fix for this is to _remove_ that feature. CWP isn't its own thing anymore.

**Comment by maxime-rainville** [comment]
Even if we don't end up supporting this officially in CMS5, I would like to have the module in a good state initially.

I'm flexible on how we get there. This could mean we take out the filter altogether.

**Comment by michalkleiner** [comment]
We always got people raising tickets around CWP reports just because they were there and the clients tested all they could find in the CMS despite not actually requiring these functions/reports, so I'd be also ok with removing that for CMS5.

**Comment by emteknetnz** [comment]
CWP will override the default supported/unsupported modules with a cwp/non-cwp filter

I've deleted the extension so the supported/unsupported module filter shows again, and I've updated it to use the official supported modules json

The filter now seems far more useful

**Comment by GuySartorelli** [comment]
PRs merged
