### ISSUE TITLE
References to installing 2.0.0 as an arbitrary example are now misleading

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp#35]
Example: https://www.cwp.govt.nz/developer-docs/en/1.8/working_with_projects/upgrading

This is an arbitrary example, but now that 2.0.0 is close to being a thing this is incorrect, since 2.0 will use different recipes.

We should change this in 1.x docs to use a 1.x release which actually exists.

**Comment by be2n** [comment]
Yes, seems sensible with the actual 2.0 recipe around the corner.

**Comment by robbieaverill** [comment]
Note: make the change in 1.4 branch and we can merge up through the others

**Comment by robbieaverill** [comment]
Fixed in #47
