### ISSUE TITLE
Review documentation in context of CWP 2.0 and SilverStripe 4

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp#42]
Ensure that the documentation that ships with CWP 2.0 is up to date and relevant for SilverStripe 4.

Tasks:

- [x] Ensure documentation is up to date and update where necessary for CWP 2.0
- [x] Add CWP 2.0 as the default docs version to the cwp.govt.nz website (note: check support timeline to determine which of the 1.x releases are still "current")
- [x] Notify CWP support of the release five days ahead of time to ensure it goes out on time - alternatively we can deploy this change now and mark it as a future version instead, then deploy a fix to switch it (still five days notice)

**Comment by robbieaverill** [comment]
Note: do this at the same time: https://github.com/silverstripe/cwp/issues/35

**Comment by chillu** [comment]
@be2n I think the "getting started" docs at https://www.cwp.govt.nz/developer-docs/en/1.8/getting_started/ should mention the different recipe variations you can install for a CWP project. By default you get the kitchen sink (e.g. a blog even if your site doesn't need one). It should clearly list the different options and what they include. Roughly speaking:

- Bare bones - SS plus CWP mandated config
- Bare bones plus recipe blog, or plus recipe collaboration, or plus recipe form-building, etc
- Default - includes all of the above
 -Agency extensions: Add to any of the above

**Comment by chillu** [comment]
Also, none of the above seems to install the actual blocks module, so that needs to be called out separately.

**Comment by chillu** [comment]
If CWP specific upgrading docs are tracked under this issue, this should probably be mentioned as an explicit goal. This needs to be a well structured document that's easy to scan and understand. It's literally the first point of contact with CWP 2.0 for most developers, and we'll heavily push this in CWP comms. If it's too confusing, devs will effectively block upgrades with "too hard" arguments. Some questions devs will have: What's new in SS4, how does that relate to what's new in CWP 2.0, what are recipes, how do I change to them, do I need to use blocks, what happens to translatable, etc, etc)

**Comment by robbieaverill** [comment]
Yeah, I hadn't originally intended this issue to cover upgrade guides, but we've made a small start here: https://github.com/silverstripe/cwp/blob/master/docs/en/05_Releases_and_changelogs/cwp_recipe_basic_2.0.0.md
