### ISSUE TITLE
Related pages autocompletion returns bad request

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp#54]
Versions:

```
cwp/cwp                                   dev-master 86bc0e0
cwp/cwp-core                              dev-master 840e633
silverstripe/cms                          4.1.x-dev 7dea009
```

On a page, when I go to Related Pages and type something into the "add existing" autocompleter I get a 302 response from the AJAX request, then a request to /admin/pages which returns a 400. This causes:

* a Bad Response toast message
* a Javascript alert telling me the request failed
* the loading spinner in the autocompleter to keep spinning indefinitely

**Comment by robbieaverill** [comment]
Still reproducible with 2.0.x-dev

**Comment by robbieaverill** [comment]
Cannot reproduce on mediumtest-uat or in SS 4.2.x-dev vanilla with symbiote/silverstripe-gridfieldextensions. @NightJar could you please try reproducing this on your environment?

**Comment by NightJar** [comment]
`cwp/cwp                                   2.0.0-rc3`

![image](https://user-images.githubusercontent.com/778003/39100777-4f553116-46e3-11e8-9f6c-1ded91fb94ed.png)

The wee dropdown did show up, but on blur (to make screenshot) it disappears again.
