### ISSUE TITLE
UX Start Time label for Event Page needs to be sanitised

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/cwp#55]
When adding an event page the label for the ‘Start Time’ field within the CMS is not properly sanitised:

![image](https://user-images.githubusercontent.com/14869519/38230007-dd9d4e10-375f-11e8-88db-286ad1276aaf.png)

To reproduce:
```
cwp/cwp-core                              dev-master 840e633
silverstripe/cms                          4.1.x-dev 7dea009
```

**Comment by robbieaverill** [comment]
Fix at #56
