### ISSUE TITLE
Docs still mention gitlab.cwp.govt.nz

### ISSUE THREAD

**Issue by chillu** [silverstripe/cwp#60]
There are 48 mentions of gitlab.cwp.govt.nz outside of the changelogs.
We've moved everything to Github a while ago, and the only way a CWP dev can figure out that they're looking at outdated repositories is by scrolling down to the README - which is easily missed.
Please update all outdated references to gitlab.cwp.govt.nz on the cwp.govt.nz docs.

**Comment by robbieaverill** [comment]
PR for the CWP 1 documentation is at #62, we'll merge it up for 2 afterwards =)

**Comment by chillu** [comment]
Nice, thank you! Merged, I'll leave the merge up to 2.x to you

**Comment by robbieaverill** [comment]
Fixed with #62
