### ISSUE TITLE
Don't allow BaseHomePage to be unpublished or deleted

### ISSUE THREAD

**Issue by madmatt** [silverstripe/cwp#69]
We seem to have a lot of issues with CMS authors accidentally unpublishing or deleting the website homepage, which leads to outages and issues with production websites that aren't easy to solve (e.g. it's hard to 'find' a deleted page).

It seems like it would make sense to implement `canUnpublish()` and `canDelete()` for the `BaseHomePage` page type here.

**Comment by robbieaverill** [comment]
Seems like a good idea to me. We could also give it a configuration flag if devs want to disable this blocking for their site, i.e. `$block_homepage_deletion = true` by default.

**Comment by andrewandante** [comment]
Are we advocating for `return false;` or `return Permission::check('ADMIN');`?

I think a lot of the people doing the unpublishing are likely to have admin permissions, so I think we almost need to have it set to straight `false`. I'm leaning slightly towards `canUnpublish()` => is ADMIN and `canDelete()` => `false`. Re-publishing is relatively easy to handle for a CMS author, but as @madmatt says, finding a "deleted" page is a bit harder.

**Comment by andrewandante** [comment]
STICKY PAGES.. no wait..

**Comment by robbieaverill** [comment]
I'd be wary of over engineering that @andrewandante. Devs can add an extension and define `canDelete() { return false; }` and apply that to certain classes

**Comment by robbieaverill** [comment]
Relevant discussion in core: https://github.com/silverstripe/silverstripe-cms/issues/2154

**Comment by madmatt** [comment]
I think actually re-publishing is actually quite difficult.

Unless this has changed, if you un-publish a root page it also un-publishes all children. If you then re-publish the root page, it does *not* re-publish all child pages (because obviously it wouldn't know if they should be published or not). So both un-publishing and deleting are equally bad in this scenario (not all sites will have pages under 'Home', but it's somewhat common to use the site tree structure in this way).

**Comment by robbieaverill** [comment]
Closing (as a duplicate) since this will be resolved in core with https://github.com/silverstripe/silverstripe-cms/issues/2154

**Comment by madmatt** [comment]
Thanks @robbieaverill!
