### ISSUE TITLE
Tag 1.8.1 doesn't reference a compatible version of 1.8

### ISSUE THREAD

**Issue by jakxnz** [silverstripe/cwp#72]
`https://github.com/silverstripe/cwp/blob/1.8.1/code/search/CwpSearchEngine.php` is not compatible  with my cwp instance `"cwp/cwp-recipe-basic": "~1.8.1@stable"`.

`https://github.com/silverstripe/cwp/blob/1.8/code/search/CwpSearchEngine.php` is compatible.

Specifically:

*Line 45*: `$query->exclude('File_ShowInSearch', 0);` is failing Solr queries on error, if the `File` class is not in the index.

`File_ShowInSearch` is not defined in the current `SolrSearchIndex` that is brought in by `"cwp/cwp-recipe-basic": "~1.8.1@stable"` requirements (`https://github.com/silverstripe/cwp-core/blob/1.8.1/code/model/SolrSearchIndex.php`)

```
ERROR org.apache.solr.core.SolrCore  â org.apache.solr.common.SolrException: undefined field File_ShowInSearch
```

`composer show cwp/cwp`

```
name     : cwp/cwp
descrip. : CWP features module. We strongly recommend using it for all new sites. Future features will be delivered here.
keywords : cwp, silverstripe
versions : * 1.8.1
type     : silverstripe-module
license  : BSD 3-Clause "New" or "Revised" License (BSD-3-Clause) (OSI approved) https://spdx.org/licenses/BSD-3-Clause.html#licenseText
source   : [git] https://github.com/silverstripe/cwp.git 22111c2b0c656251e1f15173913c789402e085e3
dist     : [zip] https://api.github.com/repos/silverstripe/cwp/zipball/22111c2b0c656251e1f15173913c789402e085e3 22111c2b0c656251e1f15173913c789402e085e3
names    : cwp/cwp

requires
cwp/cwp-core 1.8.1@stable
silverstripe/taxonomy 1.3.0@stable
```

*"stable"*

**Comment by robbieaverill** [comment]
Yes, this is an unfortunate bug. We fixed it in https://github.com/silverstripe/cwp/pull/64 for the next release, but for now you might need to subclass the search index and modify the logic. Closing since this is fixed with #64
