### ISSUE TITLE
Content block- Full screen option isn't working properly in WYSIWYG 

### ISSUE THREAD

**Issue by katieelks** [silverstripe/cwp#78]
![screen shot 2018-05-01 at 10 30 46 am](https://user-images.githubusercontent.com/38870753/39455322-ea607b92-4d33-11e8-89c3-446cbf5f01ee.png)
version 4.x tinymce

**Comment by robbieaverill** [comment]
I suspect this might also be an issue in the vanilla CMS, although the full screen option is not enabled by default

**Comment by kinglozzer** [comment]
Fixed in https://github.com/silverstripe/silverstripe-admin/pull/512

**Comment by robbieaverill** [comment]
Regressed in CWP 2.2.0-rc1 (see comments in https://github.com/silverstripe/silverstripe-admin/pull/620)

**Comment by robbieaverill** [comment]
Fixed by reverting admin#620 https://github.com/silverstripe/silverstripe-admin/commit/7538a0160c75fd5145085e15e08ba9453f86bba8
