### ISSUE TITLE
Fix broken links in developer docs

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp#82]
Google Webmaster tools has reported:

The alternating use of hyphens (-) and underscores (_) is what seems to be creating these 404s, seen here in the 1.8/performance-guide/
`https://www.cwp.govt.nz/developer-docs/en/1.8/performance-guide/` > is what is linked and returns 404
`https://www.cwp.govt.nz/developer-docs/en/1.8/performance_guide/` > is what it should be

We'll need to fix this in the lowest branch and merge up, checking as we go for new occurrences, in order to resolve all crawl errors.

**Edit:** here's the webmaster tools report for those that can access it: https://www.google.com/webmasters/tools/crawl-errors?hl=en&siteUrl=https://www.cwp.govt.nz/#t2=1

**Comment by raissanorth** [comment]
https://github.com/silverstripe/cwp/pull/83
