### ISSUE TITLE
Searching document docs indicate that textextraction is 4.0 ready

### ISSUE THREAD

**Issue by NightJar** [silverstripe/cwp#96]
The docs section for [searching (e.g. pdf) documents](https://github.com/silverstripe/cwp/blob/master/docs/en/02_Features/01_Solr_search/07_Searching_documents.md) has been updated to use SS4 syntax and namespaces, which is great. However the module itself ([silverstripe/textextraction](https://github.com/silverstripe/silverstripe-textextraction)) is only partially upgraded, and is not yet ready for prime-time use.

The docs should be updated to reflect this current status... or alternatively someone needs to hurriedly complete the upgrade for textextraction.

**Comment by robbieaverill** [comment]
It is now =)
