### ISSUE TITLE
Upgrader doesn't work on CWP 2.0 projects

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp#99]
Some of the core modules have duplicate YAML keys in their `.upgrade.yml` file mappings, which prevents the symfony/yaml package from loading them, and in turn prevents the silverstripe/upgrader tool from allowing devs to upgrade CWP 1.x projects to 2.x.

Core issue tracked here: https://github.com/silverstripe/silverstripe-upgrader/issues/72

Fix options:

* Devs can manually remove the duplicate keys from their local copies of the core repositories
* Wait for CWP 2.0.1 which will include the fixes from [this issue](https://github.com/silverstripe/silverstripe-upgrader/issues/72)

# Pull Request
* [x] https://github.com/silverstripe/silverstripe-upgrader/pull/109

**Comment by maxime-rainville** [comment]
Dammit ... I'll just fix the upgrader to allow duplicate keys and be done with it.

**Comment by robbieaverill** [comment]
If we could do both, that would be great. I've suggested we add an `.upgrade.yml` file validation step into our CI builds, which would catch this problem from occurring again. We do this already with `cow schema:validate` for cow schema file validation in recipes =)

**Comment by maxime-rainville** [comment]
Was the `.upgrade.yml` file generated manually or via `upgrade-code add-namesapce`. If it's the later, we probably need to investigate.

**Comment by robbieaverill** [comment]
Not sure - see the related PRs in the core modules (framework etc)

**Comment by robbieaverill** [comment]
Related PR is merged, this should allow duplicate YAML keys and allow devs to upgrade with bad .upgrade.yml files
